import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from './context/Store'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-[96%] h-full mx-auto my-4'>
        <StoreProvider>
          <div>
            <Navbar/>
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  )
}
